### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by AbandonedCart** [RepoDevil/Dantotsu#5]
I've noticed a lot of the stuff people have brought to me are things that were requested and even accepted, but never added. I'm aware that everyone has limitations on their time and attention, but also notice a trend that does not promote collaboration.

This fork has already progressed too far beyond the upstream source to hope that all changes will make it back, but that is no reason to slow down or stop making improvements. After all, submitting pull requests is a courtesy, not an obligation.

That said, what are your feature requests? Not all of them will be accepted and even those that are accepted may not be completed immediately, but all will be taken into consideration and decisions will be made based on viability (how possible) and compatibility (how it fits)

**Comment by OtakuVadER** [comment]
Umm Better novel support and please can you fix material you icon not working in alpha version 
![Screenshot_2024-04-04-20-48-00-23_b783bf344239542886fee7b48fa4b892](https://github.com/RepoDevil/Dantotsu/assets/88473676/0b6c2311-78f8-4547-873a-f163d984f5f5)
Ik app name is diff thats because i changed it's and package name because i wanted to keep both original and torrent dantotsu
But even before changing name and package material you icon doesn't work same in original dantotsu alpha version

**Comment by AbandonedCart** [comment]
I was thinking about breaking the package name off now that things have changed enough. All the original features are still there, though. The torrent changes overlay the existing player. Everything is done non-destructively.

**Comment by AbandonedCart** [comment]
You mean it not being in black and white?

**Comment by AbandonedCart** [comment]
Next version should fix it. It seems to be nothing more than the warnings having been ignored that the icon was too large to load.

**Comment by OtakuVadER** [comment]
Can you also send this pull request to fix in original dantotsu too?

**Comment by AbandonedCart** [comment]
During the next batch.

**Comment by OtakuVadER** [comment]
It still hasn't been fixed!!
![Screenshot_2024-04-04-22-15-50-07_b783bf344239542886fee7b48fa4b892](https://github.com/RepoDevil/Dantotsu/assets/88473676/07cad7fc-d86f-40e4-8e46-11d58d01e93f)

**Comment by OtakuVadER** [comment]
Well i tried restarting mu device and turn option on and off doesn't work

Can you try these settings
android:width="108dp"
    android:height="108dp"
    android:viewportWidth="128"
    android:viewportHeight="128"

**Comment by AbandonedCart** [comment]
@Ykuzhe I'm investigating a better backup, but I doubt it will be accepted upstream. Theirs has sentimental value.

**Comment by Ykuzhe** [comment]
I see, well, I really appreciate your effort so far on my request. Although knowing that the chances of this being accepted into the main app seems slim I still do hope that your way of making the backup system better gets accepted! Thanks again!

**Comment by AbandonedCart** [comment]
I'm sure you picked up on how talking to them is a bit of a waste because they are trying to mansplain their code, so they respond better to showing them other code that works.

**Comment by AbandonedCart** [comment]
The process is usually that I submit a PR, they take a little time to look it over and prepare some followup changes, it gets merged and then they push all their changes to it (because why discuss it in the PR, right?) and then I have to figure out why they made those changes and whether or not they simply created dead code or if there was an issue that I didn't consider. 90% of their fixes are just to disable some aspect of the code, so I usually have to follow it up with a PR that fixes it instead.

**Comment by AbandonedCart** [comment]
It's an exhausting process, which is why I stopped submitting as much.

**Comment by Ykuzhe** [comment]
I see, didn't know the scene was this bad. Surprised that you're still submitting PRs even though you're fully aware of this, I respect it. I'd be mad if someone just changed things that I created without asking me first or something.

**Comment by AbandonedCart** [comment]
Having been an Android developer for over a decade, I was the same way when I was younger.  You outgrow it eventually.

**Comment by OtakuVadER** [comment]
> The process is usually that I submit a PR, they take a little time to look it over and prepare some followup changes, it gets merged and then they push all their changes to it (because why discuss it in the PR, right?). Next, I have to figure out why they made those changes (one member just likes to reorder the layouts to look like he did something) and whether or not they simply created dead code to fix whatever issue they found. 90% of their fixes are just to disable some aspect of the code, so I usually have to follow it up with a PR that fixes it instead.

I agree with you i have submitted many bugs and devs don't even check the bugs and they just focus on hogging on more features but what they should do is fix those bugs i was telling them to fix material you icon from last 4 months did countless bug report they just ignored it in the end you were the one who fixed it and sent a pr

**Comment by AbandonedCart** [comment]
They fixed the notification bug on their own. My solution was an option that disabled the entire comments API, along with any notifications that come through it.

**Comment by OtakuVadER** [comment]
Ohkkk but still there are tons of bug

**Comment by AbandonedCart** [comment]
Unfortunately, I heard about this app from a reddit post that said something like "it looks nice, but it's supper buggy. If you want something that works, use aniyomi." I figured bugs are easier to fix than trying to create a whole new UI.

**Comment by OtakuVadER** [comment]
Well i used to be fan of Saikou it was perfect but then Dmca so I started using dantotsu but then one of my frnd gave me his id pass to a private anime streaming app (can't take name) so i have been using that and tachij2k for manga and i also have crunchyroll mod made by old kamyroll dev but still dantotsu is a feeling but now it's time to let go and use these better apps

**Comment by AbandonedCart** [comment]
I can't blame you. Ironically, I only wanted one app for both my jellyfin server and my Suwayomi server. I still haven't gotten around to including suwayomi support, though.

**Comment by OtakuVadER** [comment]
Well am interested in Android development myself but i don't have a power laptop or pc to do so.. or else i would definitely would have worked on making a app a perfect to watch anime

**Comment by AbandonedCart** [comment]
A good place to start are projects that work with decent documentation. It's much easier to see what happens when you change stuff knowing it worked and having a rough idea of how.

**Comment by OtakuVadER** [comment]
> A good place to start are projects that work with decent documentation. It's much easier to see what happens when you change stuff knowing it worked and having a rough idea of how. There is always the editor built into GitHub if hardware is the issue.

Only issue for me is how to build apk i gotta learn how to setup workflow

**Comment by AbandonedCart** [comment]
Closing this in favor of I different approach.
