### ISSUE TITLE
Material you icon not working in alpha version

### ISSUE THREAD

**Issue by AbandonedCart** [RepoDevil/Dantotsu#6]
Umm Better novel support and please can you fix material you icon not working in alpha version 
![Screenshot_2024-04-04-20-48-00-23_b783bf344239542886fee7b48fa4b892](https://github.com/RepoDevil/Dantotsu/assets/88473676/0b6c2311-78f8-4547-873a-f163d984f5f5)
Ik app name is diff thats because i changed it's and package name because i wanted to keep both original and torrent dantotsu
But even before changing name and package material you icon doesn't work same in original dantotsu alpha version

_Originally posted by @OtakuVadER in https://github.com/RepoDevil/Dantotsu/issues/5#issuecomment-2037498627_

**Comment by AbandonedCart** [comment]
Changing the size makes it load faster, which would have solved a timeout. Anything under 200 is good enough, according to Google. If that didn't solve it, then it's not the size.

**Comment by OtakuVadER** [comment]
> Changing the size makes it load faster, which would have solved a timeout. Anything under 200 is good enough, according to Google. If that didn't solve it, then it's not the size.

It works for you thou so just try setting values to what i mentioned

**Comment by AbandonedCart** [comment]
I have a feeling it works for me because of the round icons.

**Comment by OtakuVadER** [comment]
Made mine circular and doesn't work just try

android:width="108dp"
    android:height="108dp"
    android:viewportWidth="128"
    android:viewportHeight="128" 

I have a good feeling it will work

**Comment by AbandonedCart** [comment]
<details><Summary>Android Studio</summary>

![Dantotsu – mono xml  Dantotsu app main  4_4_2024 1_28_10 PM](https://github.com/RepoDevil/Dantotsu/assets/1173913/68317aed-6a0c-411f-b132-472a5c27b549)
</details>

See the big blank box to the right? That's where the icon should be.

**Comment by AbandonedCart** [comment]
The viewport is based on the original image. The only way to change it is to change the physical size of the source or rewrite the vector paths.

**Comment by OtakuVadER** [comment]
And that's missing so i was wrong ig

**Comment by OtakuVadER** [comment]
Listen listen
I have two dantotsu one is alpha and one with download feature so one with download (beta) feature supports material you icon so i extracted mono.xml from apk
[mono.xml.zip](https://github.com/RepoDevil/Dantotsu/files/14875111/mono.xml.zip)
So if you can replace this with that it should work alright?

**Comment by AbandonedCart** [comment]
I was just about to say I found the issue, but that would have at least highlighted it. It would have changed the colors, too, though.

**Comment by OtakuVadER** [comment]
> I was just about to say I found the issue, but that would have at least highlighted it. It would have changed the colors, too, though.

So it will be little different material icon ig
Let's try this file or you wanna go with your way?

**Comment by AbandonedCart** [comment]
Should work in the build that just finished.

**Comment by OtakuVadER** [comment]
Yep fixed Thanks!!
