### ISSUE TITLE
Merging subtitle sources

### ISSUE THREAD

**Issue by AbandonedCart** [RepoDevil/Dantotsu#9]
I'm still not decided on whether to combine them in a single UI or have separate buttons. I'm also not convinced the subtitle support that was present doesn't need to be rewritten.

**Comment by AbandonedCart** [comment]
@R-iscool You could also try this version and see if your issue is still present. It installs alongside theirs.

**Comment by R-iscool** [comment]
It's still present in this version.

**Comment by R-iscool** [comment]
@AbandonedCart also make sure you're watching in Hd-1 or Hd-2 server, this issue wont be present in streamtape server of hianime as in that server subtitles are pre-existing i.e. there aren't soft subtitles.

**Comment by AbandonedCart** [comment]
I should be able to fix it, but it probably won't reach the main version. They don't take responsibility for much, as you've seen.

**Comment by R-iscool** [comment]
Oh. Why dont suggest them to implement these changes. If they don't, maybe l'll use your version then 😊
Also do you know anilab, the anime app available on hianime site?So I did some research and watched the same episode of demon slayer at the same moment and guess what: there was the same issue in that app too. 
Also aniyomi doesn't have this type of issue, even wtih hianime extension.

**Comment by R-iscool** [comment]
Maybe it's the player that is different in aniyomi?

**Comment by AbandonedCart** [comment]
They use mpv.

**Comment by R-iscool** [comment]
So that's different from aniyomi?

**Comment by R-iscool** [comment]
If it is, is it possible they fix the player of dantotsu? Or use another player?

**Comment by AbandonedCart** [comment]
I'm looking into it, but it's unlikely they'll fix it. Last I heard, they intended to switch to mpv in a few months. How long it will take depends on whether they end up attempting to do it themselves or copy aniyomi.

**Comment by R-iscool** [comment]
I appreciate you trying to help a lot of people. Why do you go through so much effort when you don't need to( just asking not in a bad sense)

**Comment by AbandonedCart** [comment]
Honestly, it's because I know what it's like to get brushed off by developers and told my issues were my own fault when I knew it wasn't true. A lot of developers make empty promises. A lot of developers make excuses not to even look. When I first saw Dantotsu, what stuck out to me is a lot of "I'll look into it" posts and not a lot of meaningful progress. There is a difference between not being able to do something and being too proud to admit it.

**Comment by R-iscool** [comment]
So you intend to help people who are brushed off by Dev's?

**Comment by AbandonedCart** [comment]
Among other things, I try.

**Comment by AbandonedCart** [comment]
I can't seem to find just the right one to break it. Is there a specific resolution (720, 360, etc)?

**Comment by R-iscool** [comment]
No. Happens in Hd-1 and Hd-2 servers in with all resolutions.

**Comment by R-iscool** [comment]
I wish I coul help you , but unfortunately im not a programmer

**Comment by R-iscool** [comment]
@AbandonedCart could you somehow fix the subtitle issue in your version?

**Comment by AbandonedCart** [comment]
I have to be able to reproduce the issue first and currently AniList API is down.

**Comment by AbandonedCart** [comment]
Looks like the issue is in the subtitles being provided by the extension

**Comment by R-iscool** [comment]
But this problem isn't in the hianime.

**Comment by AbandonedCart** [comment]
Correct.

**Comment by R-iscool** [comment]
Also, for watching anime, do you use dantotsu, or any other app? Lemme know which one u use.

**Comment by R-iscool** [comment]
I can help you by telling you people's issues. is there any way we can chat in private?

**Comment by AbandonedCart** [comment]
Looks like the issue here is with ExoPlayer and the specific type of subtitles being loaded.

**Comment by R-iscool** [comment]
Is it possible to replace exo player or is it a very challenging thing to do?

**Comment by R-iscool** [comment]
@AbandonedCart new discovery! In aniyomi while I was watching ep 5 there again came a moment where two people were speaking. So i went to check it out on dantotsu/mr matagi and sure enough the subtitles were overlapping again. Seems like it really is an issue with the player. The subtitles on aniyomi were normal btw.

**Comment by AbandonedCart** [comment]
ExoPlayer has an open ticket for it. It doesn't get much more confirmed than that.

**Comment by AbandonedCart** [comment]
What were those other issues you mentioned? In the meantime, maybe I can handle some of those.

**Comment by R-iscool** [comment]
Which other issues? I didnt really get you.

**Comment by AbandonedCart** [comment]
> I can help you by telling you people's issues. 

I thought you meant there were other issues you knew about. My mistake.

**Comment by R-iscool** [comment]
Oh. I really haven't been looking. If you want me to, I'll find out some. It might take some time tho

**Comment by R-iscool** [comment]
https://github.com/rebelonion/Dantotsu/issues/349
Here's one

**Comment by AbandonedCart** [comment]
You don't have to go looking. I thought you meant you already had some issues in mind. Thanks, though.

**Comment by R-iscool** [comment]
Don't worry. I'll update you with more later.

**Comment by AbandonedCart** [comment]
No need to forward issues from the other project. That stuff already pops up because this is a fork.

**Comment by R-iscool** [comment]
So what should I do then?

**Comment by AbandonedCart** [comment]
I guess there is nothing to do, but thanks for trying.
